import {db,fail,runtime,replyError} from '@/lib/colony';
export const dynamic='force-dynamic';
const isAdmin=(r:Request)=>!!runtime().REWARDS_ADMIN_EMAIL && r.headers.get('oai-authenticated-user-email')?.toLowerCase()===runtime().REWARDS_ADMIN_EMAIL.toLowerCase();
const day=()=>new Date().toISOString().slice(0,10);
async function member(r:Request){const identity=r.headers.get('oai-authenticated-user-email');if(!identity)fail('Sign in to save colony progress.',401);const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(identity!.toLowerCase()));return Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,'0')).join('');}
async function snapshot(r:Request,m:string){const [score,total,log,submissions,queue]=await Promise.all([db().prepare('SELECT COALESCE(SUM(points),0) AS value FROM colony_points WHERE member=?').bind(m).first<{value:number}>(),db().prepare('SELECT COALESCE(SUM(points),0) AS value FROM colony_points').first<{value:number}>(),db().prepare('SELECT task,points,created FROM colony_points WHERE member=? ORDER BY created DESC LIMIT 50').bind(m).all(),db().prepare('SELECT id,kind,body,status,created FROM colony_contributions WHERE member=? ORDER BY created DESC LIMIT 20').bind(m).all(),isAdmin(r)?db().prepare("SELECT id,kind,body,created FROM colony_contributions WHERE status='pending' ORDER BY created LIMIT 50").all():Promise.resolve({results:[]})]);return {score:score?.value||0,total:total?.value||0,log:log.results,submissions:submissions.results,queue:queue.results,admin:isAdmin(r),day:day(),season:'PRE-SEASON',fundedSol:0,claimOpen:false};}
export async function GET(r:Request){try{const m=await member(r);return Response.json(await snapshot(r,m),{headers:{'Cache-Control':'no-store'}})}catch(e){return replyError(e)}}
export async function POST(r:Request){try{if(r.headers.get('origin')!==new URL(r.url).origin)fail('Invalid request origin.',403);const m=await member(r);if(Number(r.headers.get('content-length')||0)>8000)fail('Submission is too long.');const raw=await r.text();if(raw.length>8000)fail('Submission is too long.');const b=JSON.parse(raw);let awarded=0;
if(b.action==='task'){const task=b.task;if(!['checkin','learn'].includes(task))fail('Unknown task.');if(task==='learn'&&b.answer!=='confirmed-sell')fail('Choose the confirmed on-chain event that triggers transport.');awarded=task==='checkin'?10:20;const result=await db().prepare('INSERT OR IGNORE INTO colony_points(id,member,task,points,created) VALUES(?,?,?,?,?)').bind(`${m}:${day()}:${task}`,m,task,awarded,Date.now()).run();if(!result.meta.changes)fail('Already completed today. Come back after 00:00 UTC.',409);
}else if(b.action==='contribute'){if(!['bug','content','idea'].includes(b.kind)||typeof b.body!=='string'||b.body.trim().length<20||b.body.length>2000)fail('Choose a contribution type and write 20–2,000 characters.');const result=await db().prepare("INSERT INTO colony_contributions(id,member,kind,body,status,created) SELECT ?,?,?,?,'pending',? WHERE (SELECT COUNT(*) FROM colony_contributions WHERE member=? AND created>=?)<3").bind(crypto.randomUUID(),m,b.kind,b.body.trim(),Date.now(),m,Date.parse(day())).run();if(!result.meta.changes)fail('Daily submission limit reached. Try tomorrow.',429);
}else if(b.action==='review'){if(!isAdmin(r))fail('Only the colony owner can review contributions.',403);if(typeof b.id!=='string'||!['approved','rejected'].includes(b.status))fail('Invalid review.');await db().batch([db().prepare("UPDATE colony_contributions SET status=? WHERE id=? AND status='pending'").bind(b.status,b.id),db().prepare("INSERT OR IGNORE INTO colony_points(id,member,task,points,created) SELECT 'contribution:'||id,member,'contribution',50,? FROM colony_contributions WHERE id=? AND status='approved'").bind(Date.now(),b.id)]);
}else fail('Unknown action.');return Response.json({...await snapshot(r,m),awarded});}catch(e){return replyError(e)}}
