'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import ColonyRewards from '@/components/colony-rewards';
import {Bug,Plus,Minus,Sun,Crown,Activity} from 'lucide-react';
import {type ChainSale} from '@/lib/chain-feed';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {Progress} from '@/components/ui/progress';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
const usd=(v:number|null)=>v==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(v);
const role=(n:number)=>n%10===0?'Soldier':n%4===0?'Scout':'Worker';
export default function Home(){
 const [data,setData]=useState<any>(null),[tab,setTab]=useState('overview'),[selected,setSelected]=useState<number|null>(null),[camera,setCamera]=useState('nest'),[day,setDay]=useState(false),[events,setEvents]=useState<ChainSale[]>([]),[totals,setTotals]=useState({sells:0,amount:0}),[status,setStatus]=useState('Awaiting launch');
 const world=useRef<HTMLIFrameElement>(null),latest=useRef<any>(null),busy=useRef(false),seen=useRef(new Set<string>());
 const send=useCallback((msg:any)=>world.current?.contentWindow?.postMessage(msg,location.origin),[]);
 const sync=useCallback(()=>{const d=latest.current;if(d)send({type:'state',population:d.population,paused:false,active:[]});},[send]);
 useEffect(()=>{const d={population:37,market:{source:'pending',marketCap:null}};latest.current=d;setData(d);const handler=(e:MessageEvent)=>{if(e.origin!==location.origin||e.source!==world.current?.contentWindow)return;if(e.data.type==='world-ready')sync();if(e.data.type==='select-ant')setSelected(e.data.id)};addEventListener('message',handler);sync();return()=>removeEventListener('message',handler)},[sync]);
 const record=useCallback((rows:ChainSale[])=>{const fresh=rows.filter(r=>!seen.current.has(r.id));fresh.forEach(r=>seen.current.add(r.id));if(!fresh.length)return;setEvents(old=>[...fresh,...old].sort((a,b)=>b.time-a.time).slice(0,100));const sells=fresh.filter(r=>r.side==='sell');setTotals(t=>({sells:t.sells+sells.length,amount:t.amount+sells.reduce((n,r)=>n+r.quoteAmount,0)}));},[]);
 const pop=data?.population||0,m=data?.market,pct=m?.marketCap==null?0:pop>=300?100:(m.marketCap%5000)/50;
 return <div className="app"><header className="topbar"><a className="brand" href="#"><span className="brandmark"><img src="/formix-logo.jpg" alt="MYRVEX ant logo"/></span><strong>MYRVEX<span>THE LIVING COLONY</span></strong></a><nav className="project-nav" aria-label="Main navigation"><a href="#colony">Colony</a><a href="#rewards">Build & earn</a><a href="#mechanism">How it works</a><a href="#launch">Launch status</a><a href="#faq">FAQ</a><a href="https://x.com/MYRVEXsol" target="_blank" rel="noopener noreferrer">X / Twitter</a></nav><span className="network"><span className="solana-bars" aria-hidden="true"><i/><i/><i/></span>SOLANA</span></header><main className="main" style={{maxWidth:1600,margin:'auto'}}><div className="page-heading"><div><p className="eyebrow">SOLANA / COLONY OBSERVATORY</p><h1>A small world.<br/><span className="sol-gradient">A collective force.</span></h1><p className="subheading">MYRVEX turns on-chain activity into a living ant colony. Explore its chambers, meet its workers, and follow the world as it grows.</p><div className="hero-actions"><a className="primary" href="#colony">Explore the colony ↓</a><a className="outline" href="#mechanism">Understand the mechanism</a></div></div></div>
 <div className="status-strip"><span>PRE-LAUNCH</span><span>Explore mode · Official token and live feeds will be connected at launch.</span></div>
 <section className="metrics launch-metrics" aria-label="Project status"><div className="metric"><p>Project status</p><strong>PRE-LAUNCH</strong><span>Official token not yet announced</span></div><div className="metric"><p>Colony structure</p><strong>04<small>ROLES</small></strong><span>Queen · workers · scouts · soldiers</span></div><div className="metric"><p>Network</p><strong>SOLANA</strong><span>Designed around confirmed chain activity</span></div><div className="metric"><p>Access</p><strong>OPEN VIEW</strong><span>No wallet connection required to explore</span></div></section>
 <div id="colony" className="section-intro"><div><p className="eyebrow">01 / THE OBSERVATORY</p><h2>Enter the underground.</h2></div><p>Drag to orbit. Scroll to zoom. Select an ant to inspect its role.</p></div>
 <Tabs value={tab} onValueChange={setTab}><TabsList className="section-tabs" variant="line"><TabsTrigger value="overview">World view</TabsTrigger><TabsTrigger value="roster">Ant registry · {pop}</TabsTrigger><TabsTrigger value="ledger">Chain activity</TabsTrigger></TabsList>
 <TabsContent value="overview" forceMount className={tab!=='overview'?'hidden':''}><div className="world-grid"><section className="world-panel"><div className="world-title">THE UNDERGROUND · MYRVEX</div><iframe ref={world} src="/world.html" title="Interactive ant colony" className="world-frame"/><div className="world-toolbar"><div className="camera-switch">{[['nest','Underground'],['surface','Low orbit'],['queen','The queen']].map(([v,t])=><button key={v} className={camera===v?'active':''} onClick={()=>{setCamera(v);send({type:'camera',view:v})}}>{t}</button>)}</div><div className="zoom"><button aria-label="Zoom in" onClick={()=>send({type:'zoom',factor:.8})}><Plus/></button><button aria-label="Zoom out" onClick={()=>send({type:'zoom',factor:1.2})}><Minus/></button><button aria-label="Daylight" onClick={()=>{setDay(!day);send({type:'day',value:!day})}}><Sun/></button></div></div></section><aside className="queen-panel"><div className="queen-logo"><img src="/formix-logo.jpg" alt="MYRVEX"/></div><h2>The Queen</h2><div className="queen-status">{status}</div><p className="queen-copy">One colony. Four roles. Every movement is part of a shared world.</p><div className="queen-facts"><div><span>Explore-mode ants</span><strong>{pop}</strong></div><div><span>Live transaction feed</span><strong>Not connected</strong></div><div><span>Network</span><strong>Solana</strong></div></div><p className="micro">This pre-launch world runs independently of market activity. SOL coins are visual objects, not wallet balances.</p><a className="outline" href="#launch">View launch status</a></aside></div></TabsContent>
 <TabsContent value="roster"><section className="panel"><h2>Meet the colony</h2><p>Explore-mode characters. Live population will follow market capitalization after launch.</p><div className="ant-grid">{Array.from({length:pop},(_,i)=>i+1).map(n=><button className="ant-card" key={n} onClick={()=>setSelected(n)}><Bug size={35}/><strong>ANT #{n}</strong><span>{role(n)}</span></button>)}</div></section></TabsContent>
 <TabsContent value="ledger"><section className="panel"><h2><Activity/> Confirmed chain activity</h2><p>Confirmed transactions will appear here after launch.</p><div className="chain-rows">{events.map(e=><a key={e.id} href={'https://solscan.io/tx/'+e.signature} target="_blank" rel="noopener noreferrer"><b className={e.side}>{e.side.toUpperCase()}</b><strong>{e.quoteAmount.toFixed(2)} PUMP</strong><span>{new Date(e.time).toLocaleTimeString()}</span><span>View transaction ↗</span></a>)}{!events.length&&<p>Awaiting launch.</p>}</div></section></TabsContent></Tabs>

 <ColonyRewards onAward={()=>{setTab("overview");send({type:"construction-burst",amount:1});}}/>
 <section className="editorial-section" id="mechanism"><div className="section-intro"><div><p className="eyebrow">02 / THE IDEA</p><h2>Market activity.<br/><span className="sol-gradient">A world you can watch.</span></h2></div><p>MYRVEX is a visual chain observatory. It gives market data a physical form: an expanding colony, purposeful movement and a traceable transaction history.</p></div><div className="mechanism-grid">{[['01','The market sets the scale','After the official token is connected, market capitalization determines colony population: one ant per $5,000, up to 300 ants.'],['02','Confirmed sells create movement','Supported, confirmed sell events trigger a 12-second transport surge. Larger trades produce stronger movement; repeated sells extend activity.'],['03','Every event has a receipt','Received transactions link to the chain explorer. Failed transactions are excluded, and duplicate events are ignored.']].map(([n,title,body])=><article className="mechanism-card" key={n}><span className="step-number">{n}</span><h3>{title}</h3><p>{body}</p></article>)}</div><div className="mechanism-note"><strong>Activity is not income.</strong><p>A sell records a market transaction. It does not mean SOL entered a MYRVEX treasury. The colony does not custody funds or promise returns.</p></div></section>
 <section className="editorial-section"><div className="section-intro"><div><p className="eyebrow">03 / COLONY LIFE</p><h2>Different roles. One world.</h2></div><p>Each character has its own silhouette and movement. These are visual roles, not individually funded trading wallets.</p></div><div className="role-stories">{[['Queen','The center','The visual heart of the colony, surrounded by routes connecting all four resource chambers.'],['Worker','The carrier','Moves SOL coin objects between chambers and makes bursts of market activity visible.'],['Scout','The explorer','A slender silhouette with longer antennae, moving across the outer routes.'],['Soldier','The guardian','A broad head and larger mandibles distinguish the colony’s strongest silhouette.']].map(([r,title,body])=><article key={r}><div className="role-model"><iframe src={'/ant-portrait.html?role='+r} title={r+' model'} loading="lazy" tabIndex={-1}/></div><span className="eyebrow">{r}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
 <section className="editorial-section launch-section" id="launch"><div className="section-intro"><div><p className="eyebrow">04 / RELEASE STATUS</p><h2>Built to observe.<br/>Preparing to go live.</h2></div><p>The interactive world is available now. Official token details and market connections are the next release step.</p></div><div className="launch-grid"><article><h3>Available now</h3><ul><li>Interactive 3D colony and camera controls</li><li>Four character roles and close-up inspection</li><li>SOL coin resources across all four chambers</li><li>Desktop and mobile layouts</li></ul><span className="release-tag ready">READY TO EXPLORE</span></article><article><h3>At token launch</h3><ul><li>Publish the official contract address</li><li>Verify the live trading pool and quote asset</li><li>Connect market capitalization and sell events</li><li>Enable transaction links and live status</li></ul><span className="release-tag">AWAITING OFFICIAL TOKEN</span></article><article><h3>Official channels</h3><p>Follow @MYRVEXsol on X for official announcements. The official contract address will be announced here after launch.</p><p>No purchase link is active before the official token is announced.</p><a className="outline" href="https://github.com/GHOSTXrun/MYRVEX" target="_blank" rel="noopener noreferrer">View source on GitHub</a><a className="outline" href="https://x.com/MYRVEXsol" target="_blank" rel="noopener noreferrer">Follow @MYRVEXsol</a></article></div></section>
 <section className="editorial-section faq-section" id="faq"><div><p className="eyebrow">05 / QUESTIONS</p><h2>Know the colony.</h2><p>What works today, what changes at launch, and what the visuals mean.</p></div><Accordion type="single" collapsible className="faq-list">{[['What is MYRVEX?','MYRVEX is an interactive ant-colony interface for visualizing Solana token market activity. The world can be explored now; the official token feed will be connected at launch.'],['Why are the ants moving before launch?','The pre-launch colony runs an ambient animation so you can explore its design. It is not currently reacting to live buys or sells.'],['What will make the ants speed up?','Once the official pool is connected, a successfully decoded and confirmed sell can trigger a transport surge. The effect scales with trade size and fades after about 12 seconds unless another sell arrives.'],['Do the coins represent money earned?','No. The SOL coins are visual objects. Transaction volume is not profit, and the animation does not represent a project-owned wallet balance or distribute funds.'],['Do I need to connect a wallet?','No. Exploring the colony and reading public chain activity do not require a wallet connection, signature or deposit.'],['How reliable is the live feed?','The integration has been tested with confirmed trades on supported Pump.fun and PumpSwap pools. The official launch pool still needs verification. Public data sources can be delayed or rate-limited, and fallback polling may miss transactions.'],['Where is the official contract address?','It has not been announced on this site. The previous test token has been disconnected. Official details will be added here after release.']].map(([q,a],i)=><AccordionItem value={String(i)} key={q}><AccordionTrigger>{q}</AccordionTrigger><AccordionContent>{a}</AccordionContent></AccordionItem>)}</Accordion></section>
 <footer className="project-footer"><a className="brand" href="#"><span className="brandmark"><img src="/formix-logo.jpg" alt="MYRVEX ant logo"/></span><strong>MYRVEX<span>THE LIVING COLONY</span></strong></a><div><a href="#colony">Explore</a><a href="#mechanism">Mechanism</a><a href="#launch">Launch status</a><a href="#faq">FAQ</a><a href="https://x.com/MYRVEXsol" target="_blank" rel="noopener noreferrer">X / Twitter</a></div><p>Built for Solana · Pre-launch<br/>A shared world, made visible.</p></footer></main><Dialog open={selected!==null} onOpenChange={v=>{if(!v)setSelected(null)}}><DialogContent className="ant-dialog"><DialogHeader><DialogTitle>Ant #{selected}</DialogTitle><DialogDescription>{role(selected||1)} · Colony agent</DialogDescription></DialogHeader><iframe className="ant-model-portrait" src={'/ant-portrait.html?role='+role(selected||1)} title="Ant model"/><button className="primary" onClick={()=>{setTab('overview');send({type:'select',id:selected});setSelected(null)}}>Locate in world</button></DialogContent></Dialog></div>;
}
