'use client';
import {useEffect,useRef,useState} from 'react';
import {decodeTrades,TEST_MINT,TEST_POOL,type ChainSale} from '@/lib/chain-feed';
export function ChainFeed({onSell,onEvents,onStatus}:{onSell:(sol:number)=>void;onEvents?:(rows:ChainSale[])=>void;onStatus?:(status:string)=>void}){
 const [rows,setRows]=useState<ChainSale[]>([]),[status,setStatus]=useState('Connecting…'),[burst,setBurst]=useState(false);const callback=useRef(onSell);callback.current=onSell;const eventsCallback=useRef(onEvents);eventsCallback.current=onEvents;useEffect(()=>{onStatus?.(status)},[status,onStatus]);
 useEffect(()=>{let closed=false,ws:WebSocket|null=null,retry:ReturnType<typeof setTimeout>,flash:ReturnType<typeof setTimeout>,busy=false,stream=false,attempt=0;const seen=new Set<string>();
 function receive(events:ChainSale[],live=false){const fresh=events.filter(e=>!seen.has(e.id));fresh.forEach(e=>seen.add(e.id));if(seen.size>5000){const keep=[...seen].slice(-2500);seen.clear();keep.forEach(k=>seen.add(k));}if(!fresh.length)return;eventsCallback.current?.(fresh);setRows(old=>[...fresh,...old].sort((a,b)=>b.time-a.time).slice(0,20));const amount=fresh.filter(e=>e.side==='sell'&&Date.now()-e.time<30000&&e.time<Date.now()+5000).reduce((n,e)=>n+e.quoteAmount/1000,0);if(amount>0){callback.current(amount);setBurst(true);clearTimeout(flash);flash=setTimeout(()=>setBurst(false),12000);}}
 async function poll(){if(busy||closed)return;busy=true;try{const r=await fetch('/api/chain-feed');const d:any=await r.json();if(!r.ok)throw Error();if(closed)return;receive(d.trades||[]);if(!stream)setStatus(d.partial?'Limited RPC · partial recent trades':'Polling · recent 6 transactions');}catch{if(!closed&&!stream)setStatus('Feed unavailable · retrying');}finally{busy=false;}}
 function connect(){if(closed)return;ws=new WebSocket('wss://api.mainnet-beta.solana.com');ws.onopen=()=>{ws?.send(JSON.stringify({jsonrpc:'2.0',id:1,method:'logsSubscribe',params:[{mentions:[TEST_POOL]},{commitment:'confirmed'}]}));};ws.onmessage=e=>{try{const d=JSON.parse(e.data);if(d.id===1){if(d.error){ws?.close();return;}stream=true;attempt=0;setStatus('Connected · confirmed PumpSwap events');}const v=d.params?.result?.value;if(v)receive(decodeTrades(v.logs,v.signature,v.err),true);}catch{}};ws.onerror=()=>ws?.close();ws.onclose=()=>{stream=false;if(!closed){setStatus('Stream disconnected · polling fallback');retry=setTimeout(connect,Math.min(60000,5000*2**attempt++));}};}
 connect();poll();const timer=setInterval(poll,25000);return()=>{closed=true;clearInterval(timer);clearTimeout(retry);clearTimeout(flash);ws?.close();};},[]);
 return <section className={'chain-feed '+(burst?'surge':'')}><div className="chain-heading"><div><strong>{burst?'SOL TRANSPORT SURGE':'LIVE CHAIN · APU'}</strong><p>{status}</p></div><a href={'https://solscan.io/token/'+TEST_MINT} target="_blank" rel="noopener noreferrer">{TEST_MINT.slice(0,8)}…pump ↗</a></div><p className="chain-note">PumpSwap Apu/PUMP pool only · confirmed sells accelerate the ants. PUMP amounts are trade proceeds; SOL coins are visual effects, not income. Polling fallback samples recent transactions.</p><div className="chain-rows">{rows.length?rows.slice(0,6).map(e=><a key={e.id} href={'https://solscan.io/tx/'+e.signature} target="_blank" rel="noopener noreferrer"><b className={e.side}>{e.side.toUpperCase()}</b><strong>{e.quoteAmount.toFixed(2)} PUMP</strong><span>{new Date(e.time).toLocaleTimeString()}</span><span>View transaction ↗</span></a>):<p>No verified trades received yet. Waiting for network data.</p>}</div></section>;
}
