'use client';
import {useEffect,useState} from 'react';
import {Award,Check,Lock,Pickaxe,Sparkles} from 'lucide-react';
import {Progress} from '@/components/ui/progress';
type Entry={task:string;points:number;created:number};
type Submission={id:string;kind:string;body:string;status:string;created:number};
type State={score:number;total:number;log:Entry[];submissions:Submission[];queue:Submission[];admin:boolean;day:string};
const stages=[{at:100,name:'Worker chamber',reward:'Worker badge'},{at:500,name:'Scout outpost',reward:'Scout badge'},{at:2000,name:'Queen sanctuary',reward:'Colony architect badge'}];
export default function ColonyRewards({onAward,publicPreview=false}:{onAward:()=>void;publicPreview?:boolean}){
const [data,setData]=useState<State|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(''),[answer,setAnswer]=useState(''),[kind,setKind]=useState('bug'),[body,setBody]=useState('');
async function load(){setError('');try{const r=await fetch('/api/rewards',{cache:'no-store'}),d=await r.json() as State & {error?:string;awarded?:number};if(!r.ok)throw Error(d.error);setData(d);}catch(e){setError(e instanceof Error?e.message:'Unable to load progress. Retry shortly.')}}
useEffect(()=>{if(!publicPreview)load();},[publicPreview]);
async function act(payload:Record<string,string>){setBusy(payload.task||payload.action);setError('');setNotice('');try{const r=await fetch('/api/rewards',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),d=await r.json() as State & {error?:string;awarded?:number};if(!r.ok)throw Error(d.error);setData(d);if(d.awarded){setNotice(`+${d.awarded} construction points saved. The workers are carrying faster for 12 seconds.`);onAward();}else if(payload.action==='contribute'){setBody('');setNotice('Contribution received. Points are awarded only after owner review.');}else setNotice('Review saved.');}catch(e){setError(e instanceof Error?e.message:'Unable to save. Your input is preserved.');}finally{setBusy('');}}
const done=(task:string)=>!!data?.log.some(e=>e.task===task&&new Date(e.created).toISOString().slice(0,10)===data.day);
const next=stages.find(s=>s.at>(data?.total||0));
if(publicPreview)return <section id="rewards" className="editorial-section rewards-section reward-prelaunch">
<div className="section-intro"><div><p className="eyebrow">PROOF OF COLONY</p><h2>Build the nest.<br/><span className="sol-gradient">Leave your mark.</span></h2></div><p>A contribution system for the people building MYRVEX. Explore the rules below; participation opens when member accounts are ready.</p></div>
<div className="participation-banner"><div><span className="release-tag">REGISTRATION NOT OPEN</span><h3>The colony is preparing for its first builders.</h3><p>Tasks, community progress and contribution records will become available together. No action or wallet signature is required today.</p></div><a className="outline" href="https://x.com/MYRVEXsol" target="_blank" rel="noopener noreferrer">Follow launch updates on X</a></div>
<div className="reward-stats"><div><span>Your builder profile</span><strong>NOT REGISTERED</strong><small>Points appear after participation opens</small></div><div><span>Community construction</span><strong>NOT STARTED</strong><small>Progress begins with verified contributions</small></div><div><span>SOL reward season</span><strong>NOT OPEN</strong><small>No funded reward budget announced</small></div></div>
<div className="reward-workspace"><section className="reward-tasks"><div className="reward-panel-heading"><h3><Pickaxe size={21}/> Builder tasks</h3><span>PLANNED RULES</span></div><p>One completion per account per UTC day. The daily reset is 00:00 UTC / 08:00 China time.</p>{[['01','Daily check-in','10 CP','Report for duty once a day. A successful check-in will trigger a short worker transport burst.'],['02','Colony knowledge','20 CP','Answer a question about the colony. Only a correct answer will receive points.'],['03','Useful contributions','50 CP','Submit a reproducible bug, original content or a useful improvement. Points will be credited after owner approval.']].map(([n,title,points,description])=><details className="planned-task" key={n}><summary><span className="task-no">{n}</span><span><strong>{title}</strong><small>Available when participation opens</small></span><b>{points}</b></summary><p>{description}</p></details>)}<p className="micro">CP means construction points. It has no cash value and no promised token conversion.</p></section>
<aside className="nest-growth"><div className="reward-panel-heading"><h3><Sparkles size={21}/> Colony milestones</h3><span>WAITING TO BEGIN</span></div><p>Shared goals unlock community badges. These are target thresholds, not current progress.</p><div className="growth-stages">{stages.map((stage,i)=><div key={stage.at}><Lock size={20}/><div><strong>{stage.name}</strong><span>{stage.at.toLocaleString()} CP target · {stage.reward}</span></div><small className="stage-index">0{i+1}</small></div>)}</div><div className="progress-placeholder">Community progress will appear after the first verified activity.</div></aside></div>
<div className="reward-workspace"><section className="contribution-panel"><span className="eyebrow">QUALITY OVER ACTIVITY</span><h3 style={{marginTop:14}}>What counts as a contribution?</h3><ul className="contribution-guidance"><li><strong>Report an issue</strong><span>Tell us what happened, what you expected and how to reproduce it.</span></li><li><strong>Create something useful</strong><span>Share original guides, artwork or explainers with a public source link.</span></li><li><strong>Improve the colony</strong><span>Describe a concrete problem and how your proposal would solve it.</span></li></ul><p className="micro">Submission and review will open with builder accounts. Repeated or copied submissions will not qualify.</p></section><section className="season-panel"><span className="release-tag">SOL REWARDS / NOT OPEN</span><h3>A funded season comes with receipts.</h3><p>Before any SOL reward season opens, MYRVEX will publish:</p><ol><li>A treasury address and a verified funded budget.</li><li>Eligibility rules, a snapshot date and the allocation method.</li><li>A claim method and on-chain distribution records.</li></ol><p className="micro">There is currently no active claim, deposit request or guaranteed payout. Animated SOL coins are not treasury assets.</p></section></div>
</section>;
return <section id="rewards" className="editorial-section rewards-section"><div className="section-intro"><div><p className="eyebrow">PROOF OF COLONY / BUILD TOGETHER</p><h2>Every contribution.<br/><span className="sol-gradient">A stronger colony.</span></h2></div><p>Earn construction points, unlock colony badges and help the nest grow. Pre-season points are participation records, with no cash value or guaranteed token allocation.</p></div>
<div className="reward-stats"><div><span>Your construction points</span><strong>{data?data.score.toLocaleString():'—'}</strong></div><div><span>Community construction</span><strong>{data?data.total.toLocaleString():'—'} <small>CP</small></strong></div><div><span>Season treasury</span><strong>NOT FUNDED</strong><small>SOL distribution is not open</small></div></div>
{error&&<div role="alert" className="reward-alert">{error} <button className="outline" onClick={load} disabled={!!busy}>Reload progress</button></div>}{notice&&<p role="status" className="reward-success">{notice} <a href="#colony">Watch the colony</a></p>}
<div className="reward-workspace"><div className="reward-tasks"><h3><Pickaxe size={21}/> Daily construction</h3><p>Reset at 00:00 UTC. Each task can be credited once per account per day.</p><article className="reward-task"><div><h4>Report for duty</h4><p>Check in and send the workers into a transport burst.</p></div><span className="points-label">+10 CP</span><button className="primary" disabled={!data||!!busy||done('checkin')} onClick={()=>act({action:'task',task:'checkin'})}>{done('checkin')?'Completed':busy==='checkin'?'Saving…':'Check in'}</button></article>
<article className="reward-task quiz-task"><div><h4>Know your colony</h4><p>Which event will trigger market-driven transport after the official feed is connected?</p><fieldset disabled={!!busy||done('learn')}><legend className="sr-only">Choose an event</legend>{[['page-view','Someone opens the website'],['confirmed-sell','A confirmed sell from the supported official pool'],['price-rumor','A price prediction posted online']].map(([v,t])=><label key={v}><input type="radio" name="colony-quiz" value={v} checked={answer===v} onChange={()=>setAnswer(v)}/>{t}</label>)}</fieldset></div><span className="points-label">+20 CP</span><button className="primary" disabled={!data||!!busy||done('learn')||!answer} onClick={()=>act({action:'task',task:'learn',answer})}>{done('learn')?'Completed':busy==='learn'?'Saving…':'Submit answer'}</button></article>
</div><aside className="nest-growth"><h3><Sparkles size={21}/> Shared nest growth</h3><p>{next?`${Math.max(0,next.at-(data?.total||0))} CP until ${next.name}.`:'All pre-season construction milestones unlocked.'}</p><Progress value={Math.min(100,(data?.total||0)/(next?.at||2000)*100)}/><div className="growth-stages">{stages.map(s=><div key={s.at} className={(data?.total||0)>=s.at?'unlocked':''}>{(data?.total||0)>=s.at?<Check size={20}/>:<Lock size={20}/>}<div><strong>{s.name}</strong><span>{s.at.toLocaleString()} community CP · {s.reward}</span></div></div>)}</div><p className="micro">Unlocked badges are shared milestones. Your personal contribution remains recorded below.</p></aside></div>
<div className="reward-workspace"><section className="contribution-panel"><h3><Award size={21}/> Make a contribution</h3><p>Report a reproducible issue, share original content or propose a useful improvement. Approved contributions earn 50 CP. Up to three submissions per day.</p><form onSubmit={e=>{e.preventDefault();act({action:'contribute',kind,body});}}><label htmlFor="contribution-kind">Contribution type</label><select id="contribution-kind" value={kind} onChange={e=>setKind(e.target.value)}><option value="bug">Bug report</option><option value="content">Original content</option><option value="idea">Improvement idea</option></select><label htmlFor="contribution-body">Details and supporting link</label><textarea id="contribution-body" minLength={20} maxLength={2000} required rows={4} value={body} onChange={e=>setBody(e.target.value)} placeholder="Describe your contribution. For bugs, include steps to reproduce. For content, include a public link."/><button className="primary" disabled={!data||!!busy||body.trim().length<20}>{busy==='contribute'?'Submitting…':'Submit for review'}</button></form></section><section className="season-panel"><span className="release-tag">PRE-SEASON</span><h3>Build first. Fund transparently.</h3><p>Construction points are active. A funded SOL reward season has not started.</p><ol><li>The owner publishes a funded treasury address and budget.</li><li>Eligibility, snapshot date and reward rules are announced before the season.</li><li>Eligible participants claim through the published distribution method, with transaction receipts.</li></ol><button className="outline" disabled>Claims not open</button><p className="micro">There is no deposit or payment required for tasks. Transported coin graphics do not increase the treasury balance.</p></section></div>
<div className="reward-workspace"><section className="reward-history"><h3>Your construction record</h3>{!data?<p>Progress is loading or unavailable.</p>:!data.log.length?<p>No points earned yet. Complete your first daily task above.</p>:<ul>{data.log.slice(0,12).map((e,i)=><li key={i}><span>{e.task==='checkin'?'Daily check-in':e.task==='learn'?'Colony knowledge':'Approved contribution'}<small>{new Date(e.created).toLocaleString()}</small></span><strong>+{e.points} CP</strong></li>)}</ul>}</section><section className="reward-history"><h3>Your contributions</h3>{!data?.submissions.length?<p>No submissions yet.</p>:<ul>{data.submissions.map(s=><li key={s.id}><span>{s.body}<small>{s.kind} · {new Date(s.created).toLocaleDateString()}</small></span><strong>{s.status}</strong></li>)}</ul>}</section></div>
{data?.admin&&<section className="contribution-panel"><h3>Owner review queue</h3>{!data.queue.length?<p>No pending contributions.</p>:data.queue.map(s=><article key={s.id} className="review-item"><p>{s.body}</p><button className="primary" disabled={!!busy} onClick={()=>act({action:'review',id:s.id,status:'approved'})}>Approve · 50 CP</button><button className="outline" disabled={!!busy} onClick={()=>act({action:'review',id:s.id,status:'rejected'})}>Reject</button></article>)}</section>}
</section>;
}
