import { env } from 'cloudflare:workers';
export const SOL='So11111111111111111111111111111111111111112';
export const DEFAULTS={name:'MYRVEX',mint:'',usdPerAnt:5000,demoCap:185000,paused:false,live:false,automation:false,tradeSol:0.01,dailySol:0.1,slippageBps:50,holdSeconds:300};
export type Config=typeof DEFAULTS;
export const runtime=()=>env as unknown as Record<string,string>;
export function db(){if(!env.DB)throw new Error('Persistent storage is unavailable. Please retry.');return env.DB;}
export class HttpError extends Error {constructor(message:string,public status=400){super(message)}}
export function fail(message:string,status=400):never{throw new HttpError(message,status)}
export function isAdmin(r:Request){const e=runtime();return r.headers.get('oai-authenticated-user-email')?.toLowerCase()===(e.ADMIN_EMAIL||'__UNCONFIGURED__').toLowerCase();}
export function executor(r:Request){const k=runtime().EXECUTOR_TOKEN;return !!k&&k.length>=32&&r.headers.get('authorization')===`Bearer ${k}`;}
export function auth(r:Request,allowExecutor=false){if(allowExecutor&&executor(r))return;if(!isAdmin(r))fail('Only the colony owner can make changes.',403);const origin=r.headers.get('origin');if(!origin||origin!==new URL(r.url).origin)fail('Invalid request origin.',403);}
export function replyError(e:unknown){console.error(e instanceof Error?e.message:'Colony request failed');return Response.json({error:e instanceof HttpError?e.message:'Service temporarily unavailable. Your records are preserved.'},{status:e instanceof HttpError?e.status:503});}
export function mint(value:unknown){if(typeof value!=='string'||!/^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(value))fail('Enter a valid Solana mint address.');return value;}
export async function config():Promise<Config>{await db().prepare('INSERT OR IGNORE INTO settings(id,value,updated) VALUES(1,?,?)').bind(JSON.stringify(DEFAULTS),Date.now()).run();const row=await db().prepare('SELECT value FROM settings WHERE id=1').first<{value:string}>();return {...DEFAULTS,...JSON.parse(row!.value)};}
export async function event(kind:string,message:string,id=crypto.randomUUID()){await db().prepare('INSERT OR IGNORE INTO events(id,kind,message,created) VALUES(?,?,?,?)').bind(id,kind,message,Date.now()).run();}
export async function finishPaper(){const rows=await db().prepare("SELECT * FROM missions WHERE mode='paper' AND status='running' AND created<?").bind(Date.now()-18000).all<any>();for(const m of rows.results){const seed=[...m.id].reduce((n,c)=>n+c.charCodeAt(0),0);const pnl=Math.round(m.amount*((seed%61)-30)/100);await db().batch([db().prepare("UPDATE missions SET status='completed',result=?,updated=? WHERE id=? AND status='running'").bind(JSON.stringify({pnlLamports:pnl,simulated:true}),Date.now(),m.id),db().prepare('INSERT OR IGNORE INTO events(id,kind,message,created) VALUES(?,?,?,?)').bind('done-'+m.id,'paper',`Ant #${m.ant} returned. Simulated result: ${pnl>=0?'+':''}${(pnl/1e9).toFixed(5)} SOL.`,Date.now())]);}}
export async function getMarket(c:Config){if(!c.mint)return {source:'demo',marketCap:c.demoCap,price:null,change:null,updated:null,history:[]};const cache=await db().prepare('SELECT value,updated FROM market WHERE mint=?').bind(c.mint).first<{value:string,updated:number}>();if(cache&&Date.now()-cache.updated<20000)return {...JSON.parse(cache.value),updated:cache.updated,source:'live'};try{const r=await fetch('https://api.dexscreener.com/tokens/v1/solana/'+c.mint,{signal:AbortSignal.timeout(6000)});if(!r.ok)throw Error('Market upstream');const pairs:any=await r.json();const p=pairs.filter((x:any)=>x.baseToken?.address===c.mint).sort((a:any,b:any)=>(b.liquidity?.usd||0)-(a.liquidity?.usd||0))[0];if(!p||!(p.marketCap||p.fdv))throw Error('No market');const cap=Number(p.marketCap||p.fdv);const old=cache?JSON.parse(cache.value):{};const value={marketCap:cap,price:Number(p.priceUsd)||null,change:p.priceChange?.h24??null,history:[...(old.history||[]),{t:Date.now(),v:cap}].slice(-48),symbol:p.baseToken.symbol,liquidity:p.liquidity?.usd||0};await db().prepare('INSERT INTO market(mint,value,updated) VALUES(?,?,?) ON CONFLICT(mint) DO UPDATE SET value=excluded.value,updated=excluded.updated').bind(c.mint,JSON.stringify(value),Date.now()).run();return {...value,source:'live',updated:Date.now()};}catch{if(cache)return {...JSON.parse(cache.value),source:'stale',updated:cache.updated};return {source:'unavailable',marketCap:null,price:null,change:null,updated:null,history:[]};}}
export async function snapshot(r:Request){const c=await config();await finishPaper();const [m,ev,ms,totals]=await Promise.all([getMarket(c),db().prepare('SELECT * FROM events ORDER BY created DESC LIMIT 30').all(),db().prepare('SELECT id,mode,status,ant,amount,input_mint,output_mint,wallet,created,updated,result,signature FROM missions ORDER BY created DESC LIMIT 60').all<any>(),db().prepare("SELECT COUNT(*) AS completed,COALESCE(SUM(json_extract(result,'$.pnlLamports')),0) AS pnl FROM missions WHERE mode='paper' AND status='completed'").first()]);return {config:c,market:m,events:ev.results,missions:ms.results.map((x:any)=>({...x,result:x.result?JSON.parse(x.result):null})),totals,admin:isAdmin(r),serverTime:Date.now(),capabilities:{storage:true,jupiter:!!runtime().JUPITER_API_KEY,live:runtime().LIVE_TRADING_ENABLED==='true',executor:!!runtime().EXECUTOR_TOKEN},population:m.marketCap==null?0:Math.min(300,Math.floor(m.marketCap/c.usdPerAnt))};}
