import { VersionedTransaction, PublicKey } from '@solana/web3.js';
import { Buffer } from 'node:buffer';
import { auth,config,db,event,executor,fail,replyError,runtime,SOL } from '@/lib/colony';
export const dynamic='force-dynamic';
const base='https://api.jup.ag/swap/v2';
const address=(s:unknown)=>{try{return new PublicKey(String(s)).toBase58()}catch{fail('Invalid wallet address.')}};
async function upstream(path:string,init:RequestInit={}){const r=await fetch(base+path,{...init,headers:{'Content-Type':'application/json','x-api-key':runtime().JUPITER_API_KEY},signal:AbortSignal.timeout(15000)});if(!r.ok)fail('Jupiter is unavailable. No new trade was confirmed.',502);return r.json() as Promise<any>}
export async function POST(r:Request){let executingId:string|undefined;try{auth(r,true);const b:any=await r.json();if(!b||typeof b!=="object")fail("Invalid request.");const c=await config();const bot=executor(r);const e=runtime();if(c.paused)fail('Execution is paused.',409);if(!c.live||e.LIVE_TRADING_ENABLED!=='true'||!e.JUPITER_API_KEY||!c.mint)fail('Live execution is not configured. Add the mint and server API key, then explicitly enable live mode.',409);if(bot&&!c.automation)fail('Automated execution is disabled.',409);
if(b.action==='order'){
 const wallet=address(b.wallet);if(bot&&wallet!==e.EXECUTOR_WALLET)fail('Executor wallet does not match the configured address.',403);
 let inputMint=SOL,outputMint=c.mint,amount=Math.round(c.tradeSol*1e9),positionId='';
 if(b.positionId){const p=await db().prepare("SELECT * FROM missions WHERE id=? AND mode='live' AND status='confirmed' AND wallet=? AND input_mint=? AND output_mint=?").bind(String(b.positionId),wallet,SOL,c.mint).first<any>();if(!p)fail('Confirmed position not found.');const result=JSON.parse(p.result||'{}');const raw=String(result.totalOutputAmount||result.outputAmountResult||'');if(!/^\d+$/.test(raw)||Number(raw)<=0||!Number.isSafeInteger(Number(raw)))fail('Position quantity cannot be determined safely.');inputMint=c.mint;outputMint=SOL;amount=Number(raw);positionId=p.id;}
 const id=crypto.randomUUID(),now=Date.now(),day=Math.floor(now/86400000)*86400000;
 const res=await db().prepare("INSERT INTO missions(id,mode,status,ant,amount,input_mint,output_mint,wallet,created,updated,result) SELECT ?,'live','quoting',1,?,?,?,?,?,?,? WHERE NOT EXISTS(SELECT 1 FROM missions WHERE mode='live' AND status IN ('quoting','ready','submitting','uncertain')) AND (?!=? OR COALESCE((SELECT SUM(amount) FROM missions WHERE mode='live' AND input_mint=? AND created>=? AND status NOT IN ('cancelled','rejected')),0)+?<=?) AND (?='' OR NOT EXISTS(SELECT 1 FROM missions WHERE mode='live' AND json_extract(result,'$.positionId')=? AND status NOT IN ('cancelled','rejected')))").bind(id,amount,inputMint,outputMint,wallet,now,now,JSON.stringify({positionId}),inputMint,SOL,SOL,day,amount,Math.round(c.dailySol*1e9),positionId,positionId).run();
 if(!res.meta.changes)fail('Another order needs resolution, the daily budget is used, or this position already has an exit order.',409);
 try{const q=await upstream('/order?'+new URLSearchParams({inputMint,outputMint,amount:String(amount),taker:wallet,slippageBps:String(c.slippageBps)}));if(!q.transaction||!q.requestId)fail(q.errorMessage||'No executable route is available.',422);if(q.inputMint!==inputMint||q.outputMint!==outputMint||String(q.inAmount)!==String(amount)||(!Number.isFinite(Number(q.slippageBps))||Number(q.slippageBps)>c.slippageBps))fail('The returned route does not match the requested limits.',422);const tx=VersionedTransaction.deserialize(Buffer.from(q.transaction,'base64'));const signers=tx.message.staticAccountKeys.slice(0,tx.message.header.numRequiredSignatures).map(k=>k.toBase58());if(!signers.includes(wallet))fail('The transaction has an unexpected signer.',422);await db().prepare("UPDATE missions SET status='ready',quote=?,updated=? WHERE id=?").bind(JSON.stringify({...q,positionId}),Date.now(),id).run();return Response.json({id,transaction:q.transaction,requestId:q.requestId,inputMint,outputMint,inAmount:q.inAmount,outAmount:q.outAmount,slippageBps:q.slippageBps,router:q.router,expires:now+45000,mode:'live'});}catch(err){await db().prepare("UPDATE missions SET status='rejected',updated=? WHERE id=?").bind(Date.now(),id).run();throw err;}
}
if(b.action==='cancel'){const row=await db().prepare("SELECT status,created FROM missions WHERE id=? AND mode='live'").bind(String(b.id)).first<any>();if(!row)fail('Order not found.',404);if(row.status==='quoting'&&Date.now()-row.created<60000)fail('Quote is still being requested.');const result=await db().prepare("UPDATE missions SET status='cancelled',updated=? WHERE id=? AND status IN ('ready','quoting')").bind(Date.now(),String(b.id)).run();if(!result.meta.changes)fail('Submitted orders cannot be cancelled here.',409);return Response.json({ok:true});}
if(b.action==='execute'){
 const m=await db().prepare("SELECT * FROM missions WHERE id=? AND mode='live'").bind(String(b.id)).first<any>();if(!m)fail('Order not found.',404);if(m.status==='confirmed')return Response.json(JSON.parse(m.result));if(m.status!=='ready')fail('This order cannot be submitted again. Reconcile any uncertain transaction first.',409);if(Date.now()-m.created>45000)fail('Quote expired. Cancel it and request a fresh order.',409);if(bot&&m.wallet!==e.EXECUTOR_WALLET)fail('Executor wallet mismatch.',403);
 if(typeof b.signedTransaction!=='string'||b.signedTransaction.length>12000)fail('Invalid signed transaction.');const q=JSON.parse(m.quote);const signed=VersionedTransaction.deserialize(Buffer.from(b.signedTransaction,'base64'));const original=VersionedTransaction.deserialize(Buffer.from(q.transaction,'base64'));if(!Buffer.from(signed.message.serialize()).equals(Buffer.from(original.message.serialize())))fail('Transaction contents changed after quoting.');const signerIndex=signed.message.staticAccountKeys.findIndex(k=>k.toBase58()===m.wallet);if(signerIndex<0||!signed.signatures[signerIndex]?.some(x=>x!==0))fail('The configured wallet must sign this transaction.');
 const updated=await db().prepare("UPDATE missions SET status='submitting',updated=? WHERE id=? AND status='ready'").bind(Date.now(),m.id).run();if(!updated.meta.changes)fail('Order already submitted.',409);executingId=m.id;
 const result=await upstream('/execute',{method:'POST',body:JSON.stringify({signedTransaction:b.signedTransaction,requestId:q.requestId})});const ok=result.status==='Success';await db().prepare('UPDATE missions SET status=?,result=?,signature=?,updated=? WHERE id=?').bind(ok?'confirmed':result.status==='Failed'?'failed':'uncertain',JSON.stringify({...result,positionId:q.positionId||''}),result.signature||null,Date.now(),m.id).run();executingId=undefined;await event('live',ok?'Live swap confirmed on Solana.':'Live swap was not confirmed.',m.id);return Response.json(result);
}
fail('Unknown trade action.');}catch(err){if(executingId)await db().prepare("UPDATE missions SET status='uncertain',updated=? WHERE id=?").bind(Date.now(),executingId).run();return replyError(err)}}
